#!/usr/bin/env python3
"""bootstrap_companies.py — expand your company list using public
community-maintained job lists from SimplifyJobs.

Reads SimplifyJobs's machine-readable listings JSON, extracts every
Greenhouse / Lever / Ashby slug it can find, and writes them to
companies.bootstrap.yaml. pipeline.py merges this file with config.yaml
on the next run.

Caveat: SimplifyJobs is intern + new-grad focused, so the *roles* it
tracks won't match a senior search — but the *companies* are the same
companies that also post senior roles on the same boards. Expect
Greenhouse to dominate (~500-1000 slugs); Lever and Ashby coverage
will be smaller (~50-200 each), reflecting their share of the dataset.

Usage:
    python bootstrap_companies.py            # preview only
    python bootstrap_companies.py --write    # write companies.bootstrap.yaml
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

import requests
import yaml

ROOT = Path(__file__).parent
OUTPUT_PATH = ROOT / "companies.bootstrap.yaml"

# Public JSON listings from SimplifyJobs. The script tolerates any of these
# being unreachable — it merges whatever it gets.
SOURCES = [
    "https://raw.githubusercontent.com/SimplifyJobs/Summer2026-Internships/dev/.github/scripts/listings.json",
    "https://raw.githubusercontent.com/SimplifyJobs/New-Grad-Positions/dev/.github/scripts/listings.json",
]

# URL patterns for each ATS. The capture group is the company slug.
GH_PATTERN = re.compile(
    r"(?:boards|job-boards|boards-api)\.greenhouse\.io/(?:v1/boards/)?([a-z0-9_-]+)",
    re.IGNORECASE,
)
LEVER_PATTERN = re.compile(
    r"jobs\.lever\.co/([a-z0-9_-]+)",
    re.IGNORECASE,
)
ASHBY_PATTERN = re.compile(
    r"jobs\.ashbyhq\.com/([a-z0-9_-]+)",
    re.IGNORECASE,
)


def _extract_slugs(listings: list[dict], pattern: re.Pattern) -> set[str]:
    """Extract unique lowercase slugs matching pattern from listing URLs."""
    slugs: set[str] = set()
    for item in listings:
        url = item.get("url") or ""
        for m in pattern.finditer(url):
            slug = m.group(1).lower()
            # Skip slugs that look like opaque IDs (long hex hashes).
            if len(slug) > 32 and re.fullmatch(r"[a-f0-9]+", slug):
                continue
            slugs.add(slug)
    return slugs


def extract_greenhouse_slugs(listings: list[dict]) -> set[str]:
    return _extract_slugs(listings, GH_PATTERN)


def extract_lever_slugs(listings: list[dict]) -> set[str]:
    return _extract_slugs(listings, LEVER_PATTERN)


def extract_ashby_slugs(listings: list[dict]) -> set[str]:
    return _extract_slugs(listings, ASHBY_PATTERN)


def fetch_listings(url: str) -> list[dict]:
    print(f"Fetching {url}", file=sys.stderr)
    try:
        resp = requests.get(url, timeout=60)
        resp.raise_for_status()
    except requests.RequestException as exc:
        print(f"  ! {exc}", file=sys.stderr)
        return []
    try:
        data = resp.json()
    except json.JSONDecodeError as exc:
        print(f"  ! invalid JSON: {exc}", file=sys.stderr)
        return []
    return data if isinstance(data, list) else []


def main() -> None:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    ap.add_argument(
        "--write",
        action="store_true",
        help="Write companies.bootstrap.yaml (without this, just preview)",
    )
    args = ap.parse_args()

    # One pass over each source URL — extract slugs for all three ATS systems.
    gh_all: set[str] = set()
    lever_all: set[str] = set()
    ashby_all: set[str] = set()
    for url in SOURCES:
        listings = fetch_listings(url)
        gh = extract_greenhouse_slugs(listings)
        lever = extract_lever_slugs(listings)
        ashby = extract_ashby_slugs(listings)
        print(
            f"  -> {len(gh)} Greenhouse, {len(lever)} Lever, {len(ashby)} Ashby slugs",
            file=sys.stderr,
        )
        gh_all |= gh
        lever_all |= lever
        ashby_all |= ashby

    gh_sorted = sorted(gh_all)
    lever_sorted = sorted(lever_all)
    ashby_sorted = sorted(ashby_all)

    print(
        f"\nTotal unique slugs across all sources: "
        f"{len(gh_sorted)} Greenhouse, "
        f"{len(lever_sorted)} Lever, "
        f"{len(ashby_sorted)} Ashby",
        file=sys.stderr,
    )

    if not args.write:
        for label, slugs in [("Greenhouse", gh_sorted), ("Lever", lever_sorted), ("Ashby", ashby_sorted)]:
            print(f"\n--- {label} preview (first 15 of {len(slugs)}) ---")
            for slug in slugs[:15]:
                print(slug)
            if len(slugs) > 15:
                print(f"... and {len(slugs) - 15} more")
        print(f"\nRe-run with --write to save to {OUTPUT_PATH.name}.")
        return

    output = {
        "_comment": (
            "Auto-generated by bootstrap_companies.py. "
            "Re-run `python bootstrap_companies.py --write` to refresh. "
            "pipeline.py merges each list with its config.yaml counterpart."
        ),
        "greenhouse_companies": gh_sorted,
        "lever_companies": lever_sorted,
        "ashby_companies": ashby_sorted,
    }
    OUTPUT_PATH.write_text(yaml.dump(output, sort_keys=False, default_flow_style=False))
    print(
        f"Wrote {len(gh_sorted)} Greenhouse + {len(lever_sorted)} Lever + "
        f"{len(ashby_sorted)} Ashby slugs to {OUTPUT_PATH.name}.",
        file=sys.stderr,
    )


if __name__ == "__main__":
    main()
