#!/usr/bin/env python3
"""bootstrap_companies.py — expand the Greenhouse company list using
public community-maintained job lists from SimplifyJobs.

Reads SimplifyJobs's machine-readable listings JSON, extracts every
Greenhouse slug it can find, and writes them to companies.bootstrap.yaml.
pipeline.py merges this file with config.yaml on the next run.

Caveat: SimplifyJobs is intern + new-grad focused, so the *roles* it
tracks won't match a senior search — but the *companies* are the same
companies that also post senior roles on the same boards.

Usage:
    python bootstrap_companies.py            # preview only
    python bootstrap_companies.py --write    # write companies.bootstrap.yaml
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

import requests
import yaml

ROOT = Path(__file__).parent
OUTPUT_PATH = ROOT / "companies.bootstrap.yaml"

# Public JSON listings from SimplifyJobs. The script tolerates any of these
# being unreachable — it merges whatever it gets.
SOURCES = [
    "https://raw.githubusercontent.com/SimplifyJobs/Summer2026-Internships/dev/.github/scripts/listings.json",
    "https://raw.githubusercontent.com/SimplifyJobs/New-Grad-Positions/dev/.github/scripts/listings.json",
]

# Match Greenhouse URLs in any common form.
GH_PATTERN = re.compile(
    r"(?:boards|job-boards|boards-api)\.greenhouse\.io/(?:v1/boards/)?([a-z0-9_-]+)",
    re.IGNORECASE,
)


def extract_greenhouse_slugs(listings: list[dict]) -> set[str]:
    slugs: set[str] = set()
    for item in listings:
        url = item.get("url") or ""
        for m in GH_PATTERN.finditer(url):
            slug = m.group(1).lower()
            # Skip slugs that look like opaque IDs (long hex hashes).
            if len(slug) > 32 and re.fullmatch(r"[a-f0-9]+", slug):
                continue
            slugs.add(slug)
    return slugs


def fetch_listings(url: str) -> list[dict]:
    print(f"Fetching {url}", file=sys.stderr)
    try:
        resp = requests.get(url, timeout=60)
        resp.raise_for_status()
    except requests.RequestException as exc:
        print(f"  ! {exc}", file=sys.stderr)
        return []
    try:
        data = resp.json()
    except json.JSONDecodeError as exc:
        print(f"  ! invalid JSON: {exc}", file=sys.stderr)
        return []
    return data if isinstance(data, list) else []


def main() -> None:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    ap.add_argument(
        "--write",
        action="store_true",
        help="Write companies.bootstrap.yaml (without this, just preview)",
    )
    args = ap.parse_args()

    all_slugs: set[str] = set()
    for url in SOURCES:
        listings = fetch_listings(url)
        slugs = extract_greenhouse_slugs(listings)
        print(f"  -> {len(slugs)} unique Greenhouse slugs", file=sys.stderr)
        all_slugs |= slugs

    sorted_slugs = sorted(all_slugs)
    print(
        f"\nTotal unique Greenhouse slugs across all sources: {len(sorted_slugs)}",
        file=sys.stderr,
    )

    if not args.write:
        print("\n--- Preview (first 30) ---")
        for slug in sorted_slugs[:30]:
            print(slug)
        if len(sorted_slugs) > 30:
            print(f"... and {len(sorted_slugs) - 30} more")
        print(f"\nRe-run with --write to save to {OUTPUT_PATH.name}.")
        return

    output = {
        "_comment": (
            "Auto-generated by bootstrap_companies.py. "
            "Re-run `python bootstrap_companies.py --write` to refresh. "
            "pipeline.py merges this list with config.yaml's greenhouse.companies."
        ),
        "greenhouse_companies": sorted_slugs,
    }
    OUTPUT_PATH.write_text(yaml.dump(output, sort_keys=False, default_flow_style=False))
    print(f"Wrote {len(sorted_slugs)} slugs to {OUTPUT_PATH.name}.", file=sys.stderr)


if __name__ == "__main__":
    main()
